linters:
  disable-all: true
  # https://golangci-lint.run/usage/linters/
  enable:
    - errcheck # bugs, error
    - govet # bugs, metalinter 
    - staticcheck # bugs, metalinter
    - typecheck # bugs
    - ineffassign # unused
    - gofmt # format
    # - godot # style, comment
    # - gosimple # style

run:
  timeout: 2m
  allow-parallel-runners: true
  modules-download-mode: readonly
