linters:
  disable-all: true
  enable:
    - gofmt
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - godot

run:
  timeout: 2m
  allow-parallel-runners: true
  modules-download-mode: readonly
